# Generated by Django 4.1.4 on 2022-12-22 00:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
